---

stages:
  - setup
  - lint
  - test

###
# Setup
###

.activate-python-venv: &activate-python-venv
  - . venv/bin/activate

setup_environment:
  image: python:3.9.2-slim-buster
  stage: setup
  script:
    - python -m venv --copies venv
    - *activate-python-venv
    - echo $PATH
    - pip install --upgrade pip
    - pip install ${FIFTY2_PYPI_MIRROR} --requirement requirements.txt --no-cache
  artifacts:
    expire_in: 1 day
    paths:
      - venv/
  tags:
    - Docker_native_Linux

###
# Linting
###

ansible-lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint
  tags:
    - Automation

yamllint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/yamllint:latest
  script:
    - yamllint .
  tags:
    - Automation

###
# Test
###

molecule-test:
  stage: test
  needs:
    - setup_environment
  script:
    - ls -la
    - python -V
    - *activate-python-venv
    - echo $PATH
    - python -V
    - pip freeze
    - ./venv/bin/ansible --version
    - ansible --version
    - molecule test
  parallel:
    matrix:
      - MOLECULE_DISTRO: [centos7, centos8, debian10, debian11, ubuntu1804, ubuntu2004]
  tags:
    - Docker_native_Linux

