---

- block:
    - name: Generate configure script and Makefiles
      command:
        chdir: "{{ _openpbs_compile_dir }}"
        cmd: /bin/sh autogen.sh

    - name: Configure the build
      command:
        chdir: "{{ _openpbs_compile_dir }}"
        cmd: "/bin/sh configure --prefix={{ openpbs_prefix }}"

    - name: Build PBS
      make:
        chdir: "{{ _openpbs_compile_dir }}"
  become_user: "{{ openpbs_user }}"

- name: Install PBS
  make:
    chdir: "{{ _openpbs_compile_dir }}"
    target: install

- name: Configure PBS by executing the post-install script
  command:
    cmd: "{{ openpbs_prefix }}/libexec/pbs_postinstall"
  register: _openpbs_postinstall
  changed_when: false

- name: Print output of 'pbs_postinstall' command when invoked with '-v'
  debug:
    verbosity: 1
    msg: "{{ _openpbs_postinstall }}"

- name: Some file permissions must be modified to add SUID privilege
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ openpbs_prefix }}/sbin/pbs_iff"
      mode: '04755'
    - path: "{{ openpbs_prefix }}/sbin/pbs_rcp"
      mode: '04755'

