---

- name: Build OpenPBS
  block:
    - name: Generate configure script and Makefiles
      ansible.builtin.command:
        chdir: "{{ _openpbs_compile_dir }}"
        cmd: /bin/sh autogen.sh
      changed_when: false

    - name: Configure the build
      ansible.builtin.command:
        chdir: "{{ _openpbs_compile_dir }}"
        cmd: "/bin/sh configure --prefix={{ openpbs_prefix }}"
      changed_when: false

    - name: Build PBS
      ansible.builtin.make:
        chdir: "{{ _openpbs_compile_dir }}"
  become_user: "{{ openpbs_user }}"

- name: Install PBS
  ansible.builtin.make:
    chdir: "{{ _openpbs_compile_dir }}"
    target: install

- name: Configure PBS by executing the post-install script
  ansible.builtin.command:
    cmd: "{{ openpbs_prefix }}/libexec/pbs_postinstall"
  register: _openpbs_postinstall
  changed_when: false

- name: Some file permissions must be modified to add SUID privilege
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ openpbs_prefix }}/sbin/pbs_iff"
      mode: '04755'
    - path: "{{ openpbs_prefix }}/sbin/pbs_rcp"
      mode: '04755'
