---

- name: Print server- and mom-assignment (based on group membership) when invoked with '-v'
  debug:
    verbosity: 1
    msg: "server: {{ openpbs_server }}. mom: {{ openpbs_mom }}"

- name: Template /etc/pbs.conf to configure the PBS service that should be started
  template:
    src: pbs.conf.j2
    dest: /etc/pbs.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart PBS service

- name: Set own hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
    state: present
    owner: root
    group: root
    mode: '0644'

- name: Set hostname with IP 127.0.0.1 to localhost if present
  lineinfile:
    path: /etc/hosts
    regex: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost
    owner: root
    group: root
    mode: '0644'

