---

- name: Template /etc/pbs.conf to configure the PBS service that should be started
  ansible.builtin.template:
    src: pbs.conf.j2
    dest: /etc/pbs.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart PBS service
