---

###
# The downloaded file will automatically be named after the filename provided
# in the HTTP headers by GitHub and can be accessed via '_download_archive.dest'.
# It will be temporarily stored on one of the nodes which require the download.
###
- name: Download OpenPBS {{ openpbs_version }} release tarball from GitHub
  get_url:
    url: "https://api.github.com/repos/openpbs/openpbs/tarball/v{{ openpbs_version }}"
    dest: "/tmp/"
  check_mode: false
  register: _download_archive
  until: _download_archive is succeeded
  retries: 3
  delay: 5
  notify: Clean up temporary downloads
  become: false
  delegate_to: localhost
  run_once: true
