---

- name: Update package cache - Debian
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  when:
    - ansible_os_family == 'Debian'

- name: Install packages required for building OpenPBS
  ansible.builtin.package:
    name: "{{ openpbs_required_packages_build }}"
    state: present

- name: Install packages required for running OpenPBS
  ansible.builtin.package:
    name: "{{ openpbs_required_packages_run }}"
    state: present
