---

- import_tasks: preflight.yml

- name: Install required packages for building and running OpenPBS on Debian
  include_tasks: install_Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution == 'Debian'

- name: Install required packages for building and running OpenPBS on Ubuntu
  include_tasks: install_Ubuntu.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution == 'Ubuntu'

- name: Install required packages for building and running OpenPBS on CentOS
  include_tasks: install_CentOS.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'CentOS'

###
# Other distributions (we use) are not supported by OpenPBS.
###

- import_tasks: download.yml

###
# Only run this block for nodes with old versions (or absent versions, defined
# by '_openpbs_installed_version: 0.0' in 'preflight.yml').
###
- block:
    - import_tasks: unpack.yml

    - import_tasks: compile.yml
  when:
    - _openpbs_installed_version is version( openpbs_version, '<' )

- import_tasks: configure.yml

- name: Enable and start PBS service
  systemd:
    name: pbs
    enabled: true
    state: started

- import_tasks: create_queue.yml
  tags: create_queue
