---

- name: Prerequisites
  ansible.builtin.import_tasks: preflight.yml

- name: Install required packages for building and running OpenPBS
  ansible.builtin.include_tasks: install.yml

- name: Import download tasks
  ansible.builtin.import_tasks: download.yml

###
# Only run this block for nodes with old versions (or absent versions, defined
# by '_openpbs_installed_version: 0.0' in 'preflight.yml').
###
- name: Unpack and compile if outdated version of OpenPBS was found
  block:
    - name: Import unpack tasks
      ansible.builtin.import_tasks: unpack.yml

    - name: Import build tasks
      ansible.builtin.import_tasks: build.yml
  when:
    - _openpbs_installed_version is version( openpbs_version, '<' )

- name: Import configure tasks
  ansible.builtin.import_tasks: configure.yml

- name: Enable and start PBS service
  ansible.builtin.systemd:
    name: pbs
    enabled: true
    state: started
