---

- name: Set name for build directory based on OpenPBS version
  ansible.builtin.set_fact:
    _openpbs_build_dir: "{{ openpbs_build_dir }}/{{ openpbs_version }}"

- name: Create directory to unpack into
  ansible.builtin.file:
    name: "{{ _openpbs_build_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

###
# From 'man 1 tar':
# File name transformations
#   --strip-components=NUMBER
#     Strip NUMBER leading components from file names on extraction.
###
- name: Unpack OpenPBS archive
  ansible.builtin.unarchive:
    src: "{{ _download_archive.dest }}"
    dest: "{{ _openpbs_build_dir }}"
    owner: root
    group: root
    extra_opts:
      - --strip-components=1
  check_mode: false
  notify: Clean up temporary downloads
