---

- name: Clean up temporary downloads
  ansible.builtin.file:
    path: "{{ _download_archive.dest }}"
    state: absent

- name: Restart PBS service
  ansible.builtin.service:
    name: pbs
    state: restarted
