---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mpinode1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    networks:
      - name: openpbs
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
  - name: mpinode2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    networks:
      - name: openpbs
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
  - name: pbsheadnode
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    networks:
      - name: openpbs
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  connection_options:
    pipelining: false
  inventory:
    hosts:
      mpinodes:
        hosts:
          mpinode1:
          mpinode2:
      pbsscheduler:
        hosts:
          pbsheadnode:
verifier:
  name: ansible

