---

- name: Create
  hosts: all
  gather_facts: true
  become: true

  vars:
    mpi_node_user: mpiuser
    mpi_node_group: mpiuser
    mpi_node_user_home: "/home/{{ mpi_node_user }}"

  tasks:
    - name: Update package manager (Debian/Ubuntu)
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install OpenSSH packages (RedHat)
      dnf:
        name:
          - openssh-server
          - openssh-clients
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install OpenSSH packages (Debian/Ubuntu)
      apt:
        name:
          - openssh-server
          - openssh-client
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start OpenSSH server
      systemd:
        name: sshd
        state: started

    - name: Collect SSH public key from Ansible facts
      ansible.builtin.setup:
        filter:
          - 'ansible_ssh_host_key_ecdsa_public*'

    - name: Create MPI user account
      user:
        name: "{{ mpi_node_user }}"
        home: "{{ mpi_node_user_home }}"

    - name: Create .ssh directory for user {{ mpi_node_user }}
      file:
        path: "{{ mpi_node_user_home }}/.ssh/"
        state: directory
        owner: "{{ mpi_node_user }}"
        group: "{{ mpi_node_group }}"
        mode: '0700'

    - name: Generate SSH keypair for user {{ mpi_node_user }}
      openssh_keypair:
        path: "{{ mpi_node_user_home }}/.ssh/id_ed25519"
        comment: "{{ mpi_node_user }}@{{ inventory_hostname }}"
        owner: "{{ mpi_node_user }}"
        group: "{{ mpi_node_group }}"
        type: ed25519
        force: false
      register: _mpi_node_new_ssh_key

    - name: Distribute all group's SSH public keys to MPI nodes
      known_hosts:
        path: "{{ mpi_node_user_home }}/.ssh/known_hosts"
        key: >-
          {{ hostvars[item]['inventory_hostname'] }}
          {{ hostvars[item]['ansible_ssh_host_key_ecdsa_public_keytype'] }}
          {{ hostvars[item]['ansible_ssh_host_key_ecdsa_public'] }}
        state: present
        name: "{{ hostvars[item]['inventory_hostname'] }}"
      loop: "{{ ansible_play_batch }}"

    - name: Distribute SSH public keys over all MPI nodes
      authorized_key:
        user: "{{ mpi_node_user }}"
        state: present
        key: "{{ hostvars[item]['_mpi_node_new_ssh_key']['public_key'] }} {{ mpi_node_user }}@{{ item }}"
      loop: "{{ ansible_play_batch }}"

    - name: Set correct permissions for SSH known_hosts file
      file:
        path: "{{ mpi_node_user_home }}/.ssh/known_hosts"
        owner: "{{ mpi_node_user }}"
        group: "{{ mpi_node_group }}"
        mode: '0644'
